name: Test Windows
on:
  pull_request:
    branches:
      - main

jobs:
  python-module-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
          $env:Path += ';' + $env:APPDATA + '\pypoetry\venv\Scripts'
          poetry --version

      - name: Install Python Dependency
        run: |
          $env:Path += ';' + $env:APPDATA + '\pypoetry\venv\Scripts'
          poetry install
          poetry install --with=dev

      - name: Run Test
        run: |
          $env:Path += ';' + $env:APPDATA + '\pypoetry\venv\Scripts'
          poetry run python -m coverage run -m unittest
          poetry run python -m coverage xml
